---
title: "Visor de CO2"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(shiny)
library(readr)
library(ggplot2)
library(dplyr)
library(stringr)
```

Column {.sidebar}
-----------------------------------------------------------------------
Cálculo de la tasa de ventilación en un espacio - ACH

```{r}
fileInput("file1", label = "Elija su archivo txt",
            multiple = FALSE,
                accept = c("application/text",
                         ".txt"))

numericInput("co2_exterior", "Valor CO2 de referencia en exteriores", value= 400)

sliderInput("sample", label = "Muestras en datos que se deben seleccionar, para el comienzo del decaimiento de CO2 en el espacio y donde termina de decaer la concentración:",
            min = 1, max = 100, value =c(1,100))
            a("visor desarrollado por un/loquer", href="https://github.com/daquina-io/calculo-tasa-ventilacion")
```

Column
-----------------------------------------------------------------------

```{r, echo=FALSE }

df <- reactive({

        ## input$file1 will be NULL initially. After the user selects
        ## and uploads a file, head of that data file by default,
        ## or all rows if selected, will be shown.

        req(input$file1)

        ## when reading semicolon separated files,
        ## having a comma separator causes `read.csv` to error
        tryCatch(
        {
          df <- read.delim(input$file1$datapath, header = F)
          df <- df[1:dim(df)[1],] %>% str_split(" -> ") %>% unlist %>% matrix(nrow = dim(df)[1], byrow = TRUE)

          idxStartMeasurements <- which(df[,2] == "Start measurements")
          df <- df[-c(1:idxStartMeasurements), ]
          df <- df[-which(df[,2] == "Read SenseAir S8: OK DATA"),]
          df[,2] <- df[,2] %>% str_replace("CO2\\(ppm\\)\\: ","")

          df <- df %>% as.data.frame
          colnames(df) <- c("tiempo","CO2 [ppm]")
          df[,"tiempo"] <- parse_time(df[,"tiempo"])
          df[,"CO2 [ppm]"] <- as.numeric(df[,"CO2 [ppm]"])
          df
        },
        error = function(e) {
            ## return a safeError if a parsing error occurs
            stop(safeError(e))
        }
        )


        samplesLength <- dim(df)[1]
        ## Control the value, min, max, and step.
        updateSliderInput(session, "sample", value = c(1,samplesLength),
                          min = 1, max = samplesLength, step = 1)

        colnames(df) <- c("tiempo","CO2 [ppm]")

        df
  })
```


### Cálculo de la tasa de ventilación en un espacio - ACH

```{r}

renderPlot({
  ggplot(NULL, aes(x=tiempo,y=`CO2 [ppm]`)) + geom_point(data = df()[input$sample,], size = 5, col = "red") + geom_line(data= df(), col = "blue")
})
```

### Indicadores

```{r }
renderPrint({
co2_decaystart <- df()[input$sample[1],2]
t_decaystart <- df()[input$sample[1],1]
co2_tdecayend <- input$co2_exterior + (co2_decaystart-input$co2_exterior)*0.37
## Opción para calcularlo automáticamente
## co2_tdecayend <- which.min(abs(array - value))

ach <- -1*log(
(df()[input$sample[2],2] - input$co2_exterior)/
(df()[input$sample[1],2] - input$co2_exterior))/(as.numeric(df()[input$sample[2],1]-df()[input$sample[1],1])/3600)

list(
"Muestras seleccionadas para comienza_decaimiento[1] & finaliza_decaimiento[2] del aire en el espacio" = df()[input$sample,],
"Valor teórico finaliza_decaimiento[2] a buscar en los datos experimentales"=co2_tdecayend,
"Tiempo transcurrido en el decaimiento [seg]"=as.numeric(df()[input$sample[2],1]-df()[input$sample[1],1]),
"ACH"=ach[[1]]
)
})
```

